"""
SQLAlchemy Database Entity Definitions
Defensive Cybersecurity Engineering Project: Network Intrusion Detection System (IDS) Simulation

Tables:
1. network_flows: Ingested network flow metadata and classification
2. alerts: Triageable security alerts generated by IDS engines
3. rules: Configurable signature detection rules
4. incident_notes: SOC analyst investigation notes attached to alerts
5. model_results: Optional machine learning predictions and confidence scores
"""

from datetime import datetime, timezone
from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    Index,
)
from sqlalchemy.orm import relationship

from backend.database import Base


class NetworkFlow(Base):
    __tablename__ = "network_flows"

    id = Column(Integer, primary_key=True, index=True)
    flow_id = Column(String(64), unique=True, index=True, nullable=False)
    timestamp = Column(String(32), index=True, nullable=False)
    source_ip = Column(String(45), index=True, nullable=False)
    destination_ip = Column(String(45), index=True, nullable=False)
    source_port = Column(Integer, nullable=False)
    destination_port = Column(Integer, index=True, nullable=False)
    protocol = Column(String(16), index=True, nullable=False)
    packet_count = Column(Integer, default=0)
    byte_count = Column(Integer, default=0)
    duration = Column(Float, default=0.0)
    risk_score = Column(Float, index=True, default=0.0)
    classification = Column(String(32), index=True, default="NORMAL")
    scenario_type = Column(String(64), default="NORMAL_WEB")

    # Relationships
    alerts = relationship("Alert", back_populates="flow", cascade="all, delete-orphan")
    model_results = relationship("ModelResult", back_populates="flow", cascade="all, delete-orphan")

    __table_args__ = (
        Index("idx_flow_time_src", "timestamp", "source_ip"),
        Index("idx_flow_risk_class", "risk_score", "classification"),
    )


class Alert(Base):
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, index=True)
    alert_id = Column(String(64), unique=True, index=True, nullable=False)
    flow_id = Column(String(64), ForeignKey("network_flows.flow_id"), index=True, nullable=False)
    rule_id = Column(String(32), index=True, nullable=False)
    alert_type = Column(String(128), index=True, nullable=False)
    severity = Column(String(16), index=True, nullable=False)  # INFO, LOW, MEDIUM, HIGH, CRITICAL
    description = Column(Text, nullable=False)
    risk_score = Column(Float, index=True, default=0.0)
    status = Column(String(32), index=True, default="NEW")  # NEW, INVESTIGATING, RESOLVED, FALSE_POSITIVE
    created_at = Column(String(32), index=True, nullable=False)
    source_ip = Column(String(45), index=True, nullable=False)
    destination_ip = Column(String(45), nullable=False)
    source_port = Column(Integer, default=0)
    destination_port = Column(Integer, default=0)
    protocol = Column(String(16), default="TCP")

    # Relationships
    flow = relationship("NetworkFlow", back_populates="alerts")
    notes = relationship("IncidentNote", back_populates="alert", cascade="all, delete-orphan")

    __table_args__ = (
        Index("idx_alert_status_sev", "status", "severity"),
        Index("idx_alert_src_time", "source_ip", "created_at"),
    )


class Rule(Base):
    __tablename__ = "rules"

    id = Column(Integer, primary_key=True, index=True)
    rule_id = Column(String(32), unique=True, index=True, nullable=False)
    rule_name = Column(String(128), nullable=False)
    description = Column(Text, nullable=False)
    severity = Column(String(16), nullable=False)
    threshold = Column(Text, nullable=False)  # JSON-encoded threshold parameters
    enabled = Column(Boolean, default=True)


class IncidentNote(Base):
    __tablename__ = "incident_notes"

    note_id = Column(Integer, primary_key=True, index=True)
    alert_id = Column(String(64), ForeignKey("alerts.alert_id"), index=True, nullable=False)
    analyst_name = Column(String(64), default="SOC Analyst")
    note = Column(Text, nullable=False)
    created_at = Column(String(32), nullable=False)

    alert = relationship("Alert", back_populates="notes")


class ModelResult(Base):
    __tablename__ = "model_results"

    result_id = Column(Integer, primary_key=True, index=True)
    flow_id = Column(String(64), ForeignKey("network_flows.flow_id"), index=True, nullable=False)
    model_name = Column(String(64), nullable=False)
    prediction = Column(String(32), nullable=False)
    score = Column(Float, nullable=False)  # Probability or outlier score
    created_at = Column(String(32), nullable=False)

    flow = relationship("NetworkFlow", back_populates="model_results")
